.gitignore
Grimdark_Future.gst
Ratmen_Clans.cat

Added: Ratmen Clans

---

Grimdark_Future.gst
High_Elf_Fleets.cat

add: High Elf Fleets

---

.gitignore
Alien_Hives.cat

New Army: Alien Hives

---

Battle_Brothers.cat
Battle_Sisters.cat
High_Elf_Fleets.cat
Human_Defense_Force.cat
Machine_Cult.cat
Ratmen_Clans.cat
Robot_Legions.cat
readme.md

Fix: Update readme. Add missing publications. Update out of date armies

New Army: Robot Legions

---

Dark_Elf_Raiders.cat

New Army: Dark Elf Raiders

---

Dwarf_Guilds.cat
readme.md

New Army: Dwarf Guilds

---

.travis.yml
Alien_Hives.cat
Grimdark_Future.gst
Havoc_Brothers.cat
readme.md

New Army: Havoc Brothers

---

Infected_Colonies.cat
readme.md

New Army: Infected Colonies

---

.travis.yml
TAO_Coalition.cat
readme.md

New Army: TAO Coalition

---

Titan_Lords.cat
readme.md

New Army: Titan Lords

---

Grimdark_Future.gst

Updating the base GDF file to contain latest rules verbiage from the GDF Basic Rulebook v2.7. Also added and updated common weapon profiles from the last major balance overhaul.

Grimdark future v2.7 updates

---

Dwarf_Guilds.cat

Updates the Dwarf Guilds file to v2.3. Sorry for all of the commits, hopefully that doesn't make it harder to review. They were just progressive changes to the same file as I went thru unit entry-by-unit entry.

Dwarf Guilds v2.3

---

Grimdark_Future.gst
Soul_Snatchers.cat

Includes some minor tweaks and updates to the main GDF file for shared weapon options between this list, HDF, and likely upcoming Feudal Guard options.

Soul snatchers v2.6

---

Machine_Cult.cat

Bug fix for Energy Fist on the Combat Robot. This has a weaker profile than the standard Energy Fist, which I'd assumed was a mistake but OPA confirmed the weaker profile was intentional so I've added it.

Machine Cult v2.6

---

Machine_Cult.cat
readme.md

OPA put out a minor patch today correcting the Combat Robot armament. Now that these are up-to-date, I want to stay on top of them :)

Machine Cult v2.7

---

High_Elf_Fleets.cat
readme.md

High Elf Fleets v2.7

---

Human_Defense_Force.cat
readme.md

Human Defense Force v2.11

---

Dwarf_Guilds.cat
Havoc_Brothers.cat
Human_Inquisition.cat
Wormhole_Daemons.cat
readme.md

Includes minor updates for Dwarf Guilds, Havoc Brothers, Havoc Disciples, Human Inquisition and Wormhole Daemons.

09-Apr-2020 Patch

---

Alien_Hives.cat
Battle_Brothers.cat
Battle_Sisters.cat
Dark_Elf_Raiders.cat
Dwarf_Guilds.cat
Elven_Jesters.cat
Feudal_Guard.cat
Grimdark_Future.gst
Havoc_Brothers.cat
High_Elf_Fleets.cat
Human_Defense_Force.cat
Human_Inquisition.cat
Infected_Colonies.cat
Machine_Cult.cat
Orc_Marauders.cat
Ratmen_Clans.cat
Robot_Legions.cat
Soul_Snatchers.cat
TAO_Coalition.cat
Titan_Lords.cat
Wormhole_Daemons.cat
readme.md

Bringing all supported army lists up-to-date as well as addressing known bugs.

Psychic Powers Overhaul

---

Human_Defense_Force.cat

Accidentally had Veteran upgrades in the Storm Troopers unit entry instead.

Fix upgrades for Veterans & Storm Troopers

---

Havoc_Brothers.cat

Was missing some costs on Plague Brother Destroyers' weapon options.

Plague Bros - Cost Fixes

---

Custodian Brothers.cat

Fixed Custodian Heavy Walker base cost

Fix Issue #116

---

Battle_Brothers.cat
Battle_Sisters.cat
Havoc_Brothers.cat
High_Elf_Fleets.cat

Replaced collective entry with a local one.

A bunch of fixes

---

Battle_Brothers.cat
readme.md

Updated point cost of Prime Brothers

Prime Brothers v2.15

---

Alien_Hives.cat

Alien Hives - Adds hook weapons to Hive Warriors.

Alien Hives - Fixes ranged weapon costs for Hive Lord and Prime Warrior.

---

Alien_Hives.cat

Fixes Hive Warrior Bio-Spitter cost (Fixes #138)
Fixes Shredder Bio-Artillery cost.

Fixes Alien Hives upgrade costs.
